name: functional_error_handling
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Functional programming
  dartz: ^0.10.1
  # State management
  flutter_bloc: ^8.0.1
  # Value equality
  equatable: ^2.0.3
  # Sealed classes
  freezed_annotation: ^1.1.0
  # JSON serialization
  json_annotation: ^4.4.0
  # API call
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^1.1.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
